spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false
    cron: ${CRON}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  port: ${SERVER_PORT}

logging.level.org.springframework.boot.autoconfigure: ERROR