version: '3.3'
services:
  backend:
    container_name: mojito-server
    build:
      context: ..
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    container_name: auth-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0