## Variables

@content = 힘내세요!
@edit_content = edit 힘내세요!dd

@post-id = 2
@comment-id = 1

####  로그인
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.log("Authorization: " + response.headers.valueOf("Authorization"));

  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
  client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}


### 댓글 작성
POST http://localhost:8080/posts/{{post-id}}/comments
Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{content}}"
}



### 댓글 수정
PATCH http://localhost:8080/posts/{{post-id}}/comments/{{comment-id}}
Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{edit_content}}"
}


### 댓글 삭제
DELETE http://localhost:8080/posts/{{post-id}}/comments/{{comment-id}}
Authorization:{{Authorization}}
Content-Type: application/json



### 댓글 조회
GET http://localhost:8080/posts/{{post-id}}/comments?page=0
Authorization:{{Authorization}}





