## Variables
@username = fltnsah121
@password = test@1231

@content = 힘내세요!
@edit_content = edit 힘내세요!dd

@post-id = 24

####  로그인
#POST http://localhost:8080/v1/login
#Content-Type: application/json
#
#{
#  "username": "{{username}}",
#  "password": "{{password}}"
#}
#
#> {%
#  client.global.set("Authorization", response.headers.valueOf("Authorization"));
#%}




### 댓글 작성
POST http://localhost:8080/posts/{{post-id}}/comments
#Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{content}}"
}



### 댓글 수정
PATCH http://localhost:8080/posts/{{post-id}}/comments/4
Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{edit_content}}"
}


### 댓글 삭제
DELETE http://localhost:8080/posts/{{post-id}}/comments/5
Authorization:{{Authorization}}
Content-Type: application/json



### 댓글 조회
GET http://localhost:8080/posts/{{post-id}}/comments?page=0






