//로컬테스트는 localhost 입력
@host = localhost
@plan-id = 10

### 로그인
POST http://{{host}}:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.log("Authorization: " + response.headers.valueOf("Authorization"));

  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
  client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}

### 인증 코드 전송
POST http://{{host}}:8080/v1/plans/{{plan-id}}/invite
Content-Type: application/json
Authorization: {{Authorization}}

{
  "email": "chmh3370@gmail.com"
}


### 인증 코드 확인, 공동 작업자 추가
GET http://{{host}}:8080/v1/plans/{{plan-id}}/invite?authCode=
Content-Type: application/json
Authorization: {{Authorization}}


