### 로그인
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.log("Authorization: " + response.headers.valueOf("Authorization"));

    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
    client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}

### 인증 코드 전송
POST http://localhost:8080/v1/plans/invite
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}

{
  "email" : "chyj2108@naver.com"
}


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}

### 인증 코드 확인, 공동 작업자 추가
POST http://localhost:8080/v1/plans/1/authCode
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}

{
  "authCode": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaHlqMjEwOEBuYXZlci5jb20iLCJleHAiOjE3MjI1Mzc5NDcsImlhdCI6MTcyMjUzNjE0N30.pdA1jw8hlGLAtGWVLSDCSAtAsciIcT9pP-jakY-P5Lw"
}


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}