### 로그인
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.log("Authorization: " + response.headers.valueOf("Authorization"));

    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
    client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}

### 인증 코드 전송
POST http://localhost:8080/v1/plans/invite
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}

{
  "email" : ""
}


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}

### 인증 코드 확인, 공동 작업자 추가
POST http://localhost:8080/v1/plans/1/authCode
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}

{
  "authCode": ""
}


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}