## Variables



@contentId = 9
@contentType_post = post
@contentType_comment = comment

//로컬테스트는 localhost 입력
@host = 15.164.59.0

### 로그인
POST http://{{host}}:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.log("Authorization: " + response.headers.valueOf("Authorization"));

  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
  client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}



### 좋아요 작성 - post
POST http://{{host}}:8080/posts/2/likes
Authorization:{{Authorization}}
Content-Type: application/json





### 좋아요 작성 - comment
POST http://{{host}}:8080/comments/1/likes
Authorization:{{Authorization}}
Content-Type: application/json





