## Variables


@post-id = 7

@title = title12
@content = content
@theme = THRILL
@address = 서울 동작구 사당동 134-1
@place-name = 이수역꼬치거리

@edit_title = title12 edit
@edit_content = content edit
@edit_theme = CAMPING
@edit_address = 서울 동작구 사당동 134-1 edit
@edit_place-name = 이수역꼬치거리 edit

@region = 서울 동작구
#createdAt    viewsCount   likesCount
@sort-by = viewsCount
@q =


#
### 로그인
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.log("Authorization: " + response.headers.valueOf("Authorization"));

  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
  client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}




### 글 작성
POST http://localhost:8080/v1/posts
Authorization:{{Authorization}}
Content-Type: application/json

{
  "title": "{{title}}",
  "content": "{{content}}",
  "theme" : "{{theme}}",
  "address" : "{{address}}",
  "placeName" : "{{place-name}}",
  "imageIdList": [11]
}



### 글 삭제
DELETE localhost:8080/v1/posts/{{post-id}}
Authorization:{{Authorization}}


### 글 조회 (장소명으로 그룹지어 조회)
GET localhost:8080/v1/posts/place-name
    ?page=1&theme={{theme}}&region={{region}}
Authorization:{{Authorization}}


### 글 아이디 제목 조회
GET localhost:8080/v1/posts
    ?place-name={{place-name}}&page=0&q={{q}}&sort-by={{sort-by}}
Authorization:{{Authorization}}

### 내가 쓴 글 아이디 제목 조회
GET localhost:8080/v1/posts/me
    ?page=0&q={{q}}&sort-by={{sort-by}}
Authorization:{{Authorization}}




### 글 수정
PATCH localhost:8080/v1/posts/{{post-id}}
Authorization:{{Authorization}}
Content-Type: application/json

{
  "title": "{{edit_title}}",
  "content": "{{edit_content}}"
}



### 글 단권 조회
GET localhost:8080/v1/posts/{{post-id}}
Authorization:{{Authorization}}
