name: Java CI with Gradle


on:
  push:
    branches: [ develop, feat/*, feat/**, fix/**, refactor/**, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17 with OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        #환경변수 입력
      - name: Get production environment variables
        run: |
          touch ./.env.production
          echo "${{ secrets.PRODUCTION_ENV }}" > ./.env.production
        shell: bash
        #권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Spring Boot 어플리케이션 Build (1)
      - name: Spring Boot Build
        run: ./gradlew clean build --exclude-task test
